### ISSUE TITLE
fish$go returns output before analysis is complete

### ISSUE THREAD

**Issue by prescient** [curso-r/stockfish#12]
When looking at a position fish$go will return an info message prior to search completion. For example: "info depth 22 currmove a3d6 currmovenumber 1"

It isn't clear how you wait for results (e.g. search to depth x). If this is straight and I've missed it perhaps adding an example to the documentation is all that is needed.

**Comment by clente** [comment]
There are three arguments that can help you with your problem: `depth`, `nodes`, and `movetime`. You can find more information about them by checking out the documentation for the `fish` class

```r
?stockfish::fish
```

Does this solve your issue?

**Comment by prescient** [comment]
I'm not quite sure why but sometimes both of fish$go(depth = 25) and fish$output return NULL. It appears to be a bit random as I'm looping over FENs.

My code is something to the effect of the following. In the output you will (hopefully) notice that null results are returned in some cases. I have noticed that I can wrap the go statement in a while loop and request another eval if the first eval returned is null and that usually solves the issue.

```
require(stringr)
require(stockfish)

threads   <- 8
hash_size <- 2048
depth     <- 25
fen       <- c("[FEN \"3q4/k2r1R2/1p6/p7/8/Q6P/6PK/8 w - - 0 1\"]", 
               "[FEN \"6k1/4K1b1/8/4R3/8/8/8/8 w - - 0 0\"]", 
               "[FEN \"8/8/8/8/5q2/4k2K/6R1/8 w - - 0 1\"]", 
               "[FEN \"8/8/8/3r4/B3k3/3r4/4K3/8 w - - 0 1\"]", 
               "[FEN \"7k/1p1P1p1p/1Nn5/B4pb1/2P5/7P/1P3r2/1K1R4 w - - 0 1\"]", 
               "[FEN \"6k1/1p5p/2P1p3/pP1pN2q/P2Qpr2/7b/5R1P/6K1 b - - 0 1\"]", 
               "[FEN \"r1bqkb1r/pp1npppp/2p2n2/8/4N3/5N2/PPPPQPPP/R3KB1R w KQkq - 0 1\"]", 
               "[FEN \"r1b1kb1N/ppp3pp/2q2n2/4p3/2Bn4/8/PPPP1PPP/RBNQK2R b KQq - 0 1\"]", 
               "[FEN \"7k/4p3/3b4/8/3R4/8/5K2/8 b - - 0 1\"]", 
               "[FEN \"rn1qkb1r/ppp1pppp/5n2/8/2B3b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1\"]", 
               "[FEN \"3rq3/ppRr2kp/3Rp1p1/4Pp2/2Q2P2/8/PP4PP/6K1 w - - 0 1\"]", 
               "[FEN \"rnbqkb1r/pppp1ppp/8/4N3/4n3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 1\"]", 
               "[FEN \"rn1qkbnr/ppp2pp1/3p3p/4p3/2B1P1b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1\"]", 
               "[FEN \"1r4k1/1r1q1pp1/7p/pb1p4/8/4P1P1/QR3P1P/1R3BK1 w - - 0 1\"]", 
               "[FEN \"r4bk1/2p2pp1/7p/3br1q1/1p2B3/4RQ1P/PP3PP1/R4NK1 b - - 0 1\"]", 
               "[FEN \"5rk1/5pbp/3pb1p1/qp1N3P/2r5/1QP5/1K2NPP1/3R3R b - - 0 1\"]", 
               "[FEN \"5k2/R4p1p/1nr1pbp1/8/8/1P2B2P/3N1PP1/6K1 w - - 0 1\"]", 
               "[FEN \"r2q1rk1/1b2bp2/ppn1p1p1/3P2Np/2P4Q/P2B4/1B3PPP/R4RK1 w - - 0 1\"]", 
               "[FEN \"r2qkb1r/ppp1pppp/3p1n2/3Pn3/2P3b1/2N5/PP1NPPPP/R1BQKB1R b KQkq - 0 1\"]", 
               "[FEN \"2b2r1k/1p2qp1p/p1rp1b2/5p2/3BP2P/7B/PPPQ4/1K3RR1 w - - 0 1\"]"
)

# clean up fen from chessbase pgn
fen <- str_sub(fen, 7, str_length(fen) - 2)
eng <- fish$new(path = NULL)
eng$setoption("Threads", value = threads)
eng$setoption("Hash", value = hash_size)

count <- 1
for(i in fen){
  eng$ucinewgame()
  eng$position(i)
  res <- eng$go(depth = depth)
  flush.console()
  print(paste0(count, ": ", res))
  count <- count + 1
}

eng$quit()
```

**Comment by clente** [comment]
As far as I can tell, this is not a bug with `{stockfish}`. The issue is that Stockfish (the engine itself) takes some time to compute the query, and, to be more precise, it takes an _unpredictable_ amount of time. Because of the UCI protocol, engines actually start calculations before you issue the `go` command, and they might continue even past the point you tell them to stop.

This means that I can never be sure whether the engine is done with what the user has requested. If `{stockfish}` queries the engine twice, and, if nothing has changed, it returns the result; but that could happen any time the engine hangs between two steps of the computation.

One possible workaround is waiting before running `go`. E.g., the code bellow didn't return any `NULL`s:

```r
devtools::load_all()
require(stringr)

threads   <- 8
hash_size <- 2048
depth     <- 25
fen       <- c("[FEN \"3q4/k2r1R2/1p6/p7/8/Q6P/6PK/8 w - - 0 1\"]", 
               "[FEN \"6k1/4K1b1/8/4R3/8/8/8/8 w - - 0 0\"]", 
               "[FEN \"8/8/8/8/5q2/4k2K/6R1/8 w - - 0 1\"]", 
               "[FEN \"8/8/8/3r4/B3k3/3r4/4K3/8 w - - 0 1\"]", 
               "[FEN \"7k/1p1P1p1p/1Nn5/B4pb1/2P5/7P/1P3r2/1K1R4 w - - 0 1\"]", 
               "[FEN \"6k1/1p5p/2P1p3/pP1pN2q/P2Qpr2/7b/5R1P/6K1 b - - 0 1\"]", 
               "[FEN \"r1bqkb1r/pp1npppp/2p2n2/8/4N3/5N2/PPPPQPPP/R3KB1R w KQkq - 0 1\"]", 
               "[FEN \"r1b1kb1N/ppp3pp/2q2n2/4p3/2Bn4/8/PPPP1PPP/RBNQK2R b KQq - 0 1\"]", 
               "[FEN \"7k/4p3/3b4/8/3R4/8/5K2/8 b - - 0 1\"]", 
               "[FEN \"rn1qkb1r/ppp1pppp/5n2/8/2B3b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1\"]", 
               "[FEN \"3rq3/ppRr2kp/3Rp1p1/4Pp2/2Q2P2/8/PP4PP/6K1 w - - 0 1\"]", 
               "[FEN \"rnbqkb1r/pppp1ppp/8/4N3/4n3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 1\"]", 
               "[FEN \"rn1qkbnr/ppp2pp1/3p3p/4p3/2B1P1b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1\"]", 
               "[FEN \"1r4k1/1r1q1pp1/7p/pb1p4/8/4P1P1/QR3P1P/1R3BK1 w - - 0 1\"]", 
               "[FEN \"r4bk1/2p2pp1/7p/3br1q1/1p2B3/4RQ1P/PP3PP1/R4NK1 b - - 0 1\"]", 
               "[FEN \"5rk1/5pbp/3pb1p1/qp1N3P/2r5/1QP5/1K2NPP1/3R3R b - - 0 1\"]", 
               "[FEN \"5k2/R4p1p/1nr1pbp1/8/8/1P2B2P/3N1PP1/6K1 w - - 0 1\"]", 
               "[FEN \"r2q1rk1/1b2bp2/ppn1p1p1/3P2Np/2P4Q/P2B4/1B3PPP/R4RK1 w - - 0 1\"]", 
               "[FEN \"r2qkb1r/ppp1pppp/3p1n2/3Pn3/2P3b1/2N5/PP1NPPPP/R1BQKB1R b KQkq - 0 1\"]", 
               "[FEN \"2b2r1k/1p2qp1p/p1rp1b2/5p2/3BP2P/7B/PPPQ4/1K3RR1 w - - 0 1\"]"
)

# clean up fen from chessbase pgn
fen <- str_sub(fen, 7, str_length(fen) - 2)
eng <- fish$new()
eng$setoption("Threads", value = threads)
eng$setoption("Hash", value = hash_size)

count <- 1
for(i in fen){
  eng$ucinewgame()
  eng$position(i)
  Sys.sleep(5) # <- wait before asking for results
  res <- eng$go(depth = depth)
  flush.console()
  print(paste0(count, ": ", res))
  count <- count + 1
}

eng$quit()
```

This is by no means a solution, but it might help with your problem. If you ever find another package that solves this (maybe in Python?), please let me know so that I can implement it.

P.S.: If you run `fish$go(infinite = TRUE)` and then `fish$stop()`, it always returns a valid result afaik.

**Comment by prescient** [comment]
I honestly don't know how helpful this will be but the python chess package looks pretty comprehensive: https://python-chess.readthedocs.io/en/latest/engine.html

I'll also link the julia puzzle generator code as it was written by tord romstadt: https://github.com/Play-Magnus/PuzzleGenerator

**Comment by clente** [comment]
I'm pretty familiar with `python-chess` (I even made [an R package](https://github.com/curso-r/chess) using it as a back-end), and it [seems](https://github.com/niklasf/python-chess/blob/a40f2e84139dd90c0cc9207c72f9b36f5454430b/chess/engine.py#L2230) like it parses the output and actively looks for the depth the user asked for. I'm not really a fan of this approach because it has the potential of making the I/O loop much more expensive. As for Julia, I will take a look at what they do.

I will consider parsing the output for the next release of `{stockfish}`. I'm currently having some trouble getting it back on CRAN, so I have to fix this first before adding more functionality.

**Comment by prescient** [comment]
Very cool. I'll take a look at your chess package. That looks like the exact sort of thing I'm looking for.
